### ISSUE TITLE
Can't train outputted embeds

### ISSUE THREAD

**Issue by minermanb** [tkalayci71/embedding-inspector#2]
When I try to train an embed I mixed, it gave me this error. Is it not writing a value for training steps?
```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 315, in train_embedding
    scheduler.apply(optimizer, embedding.step)
  File "C:\stable-diffusion-webui\modules\textual_inversion\learn_schedule.py", line 62, in apply
    if step_number < self.end_step:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
Maybe have some sort of option to add the training step value of the highest-weighted embedding, or a weighted average, or even just an input field? The mixed embed is better than its original and I'd like to use it as a basis for training. Attempting to do a "data transplant" using the embeds as zip files doesn't work either.

**Comment by tkalayci71** [comment]
Hi, thanks for submitting this issue. I havent' done any training myself so I didn't test it with that. I will try to check it out and fix the issue as soon as possible.

**Comment by minermanb** [comment]
Seems to be working. I'll have to wait for the preview images to see whether it completely screwed it up though.

**Comment by minermanb** [comment]
Yep, it's working, the previews look good.
