### ISSUE TITLE
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#22]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\embedding-inspector\scripts\embedding_inspector.py", line 228, in do_inspect
    plt.plot(x.numpy(), emb_vec[u].numpy())
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

Not sure what is going on now but everything lights up with ERROR.

**Comment by DarkAlchy** [comment]
> I couldn't reproduce but just uploaded emergency bugfix anyway, please test.. thanks!

Just tested it and it worked.

Thanks again.

**Comment by tkalayci71** [comment]
phew, thank you!
