### ISSUE TITLE
Another tensor related issue.

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#23]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 598, in process_images_inner
    c = get_conds_with_caching(prompt_parser.get_multicond_learned_conditioning, prompts, p.steps, cached_c)
  File "D:\stable-diffusion-webui\modules\processing.py", line 565, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "D:\stable-diffusion-webui\modules\prompt_parser.py", line 205, in get_multicond_learned_conditioning
    learned_conditioning = get_learned_conditioning(model, prompt_flat_list, steps)
  File "D:\stable-diffusion-webui\modules\prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 220, in forward
    z = self.process_tokens(tokens, multipliers)
  File "D:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 245, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "D:\stable-diffusion-webui\modules\sd_hijack_open_clip.py", line 28, in encode_with_transformers
    z = self.wrapped.encode_with_transformer(tokens)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 175, in encode_with_transformer
    x = x + self.model.positional_embedding
RuntimeError: The size of tensor a (119) must match the size of tensor b (77) at non-singleton dimension 1

I just finished combining two of my embeddings that I created, and the one this created gives me that error when I call it.

**Comment by tkalayci71** [comment]
I reproduced this, by concatenating too many vectors beyond 77 token limit. Unfortunately it's a webui issue, you might want to open one there. What I can do is not drawing too many vectors in graph and showing a warning if vector count>77.

**Comment by DarkAlchy** [comment]
Thing is I see the 119 and 77 token limit but I don't have any embeddings that even if I added them all up would go over 77.  These were my embs and I use 8 or 16 vectors (some were 1 vector).

**Comment by tkalayci71** [comment]
Then either concat mode was selected by mistake, or another bug somewhere..
I have already added the warning and also showing final vector count.

**Comment by tkalayci71** [comment]
wait don't download latest commit, it's a bad fix I must revert

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/212345497-a48e8c0d-5b97-4bec-96fa-5dd6ed96fdeb.png)

**Comment by tkalayci71** [comment]
so... is it working or do you still get that 119 error? what's the prompt, does list loaded embeddings show any with too many vectors?

**Comment by DarkAlchy** [comment]
I don't have any that would push it over 77 to try. :/

**Comment by tkalayci71** [comment]
I can't change color but I can add some red emoji I think

**Comment by tkalayci71** [comment]
done, v2.83, I hope this is a stable version, I don't want to mess with it anymore.
thanks
