### ISSUE TITLE
Does not seem to work at all - possible conflict with another extension?

### ISSUE THREAD

**Issue by orcinus** [tkalayci71/embedding-inspector#29]
Typing "cat" ast the token and hitting Inspect results in this terminal message:
`Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5`

and just `150` in the output box.
Same happens with any other token.
None of the other functionality works and throws exceptions all over the place, e.g.

```
Traceback (most recent call last):
  File "E:\Documents\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Documents\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Documents\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Documents\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 540, in preprocess
    return self._round_to_precision(x, self.precision)
  File "E:\Documents\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 504, in _round_to_precision
    return int(round(num, precision))
TypeError: type str doesn't define __round__ method
```

I suspect there's a conflict with some other extension, dreambooth perhaps?
Any ides?

**Comment by tkalayci71** [comment]
Hi, I could't reproduce it. I installed dreambooth, it didn't quite work but no such error either. Maybe you could try disabling extensions untill the error goes away? sorry
