### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.sd_hijack_open_clip'

### ISSUE THREAD

**Issue by coronet1127** [tkalayci71/embedding-inspector#3]
Error loading script: embedding_inspector.py
Traceback (most recent call last):
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\embedding-inspector\scripts\embedding_inspector.py", line 10, in <module>
    from modules.sd_hijack_open_clip import tokenizer as open_clip_tokenizer
ModuleNotFoundError: No module named 'modules.sd_hijack_open_clip'

**Comment by tkalayci71** [comment]
Hi, this error occurs if your webui is not up to date (you need to do a git pull). However if you don't want to update webui, I've also made a fix for my extension, it should work if you get the current fixed version.

**Comment by coronet1127** [comment]
Thanks!
