### ISSUE TITLE
Stopped working with vlad's SD.Next

### ISSUE THREAD

**Issue by Threnos** [tkalayci71/embedding-inspector#36]
Hello!
This extention used to work with [SD.Next](https://github.com/vladmandic/automatic) and I found it super useful. However, after a big update of the fork, it started throwing an error when trying to search for a token:
```
Traceback (most recent call last):
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/metalFlash/extensions/embedding-inspector/scripts/embedding_inspector.py", line 208, in do_inspect
    scores = cos(all_embs, vec_v)
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/metalFlash/venv/lib/python3.10/site-packages/torch/nn/modules/distance.py", line 87, in forward
    return F.cosine_similarity(x1, x2, self.dim, self.eps)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by NoYzE1** [comment]
Had the same error with a recent update of 1111.
It looks like something in torch changed about how it handles the input of the second Tensor.

The Dimension of 'vec_v' is a 1D Tensor and 'all_embs' is a 2D Tensor but Torchs CosineSimilarity seem to expect the same Dimension on both Tensors now.

I fixed it for me by changing the file 'embedding_inspector.py'.
In the function 'do_inspect' i added the line:

`vec_v = vec_v.view(1, -1)`

before the call to cos resulting in this code to add another Dimension to the Tensor:
```
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
vec_v = vec_v.view(1, -1)
scores = cos(all_embs, vec_v)
```

With this change, at least the inspecting of embeddings works again as expected. Saving mixed doesn't seem to work though.
But maybe this is a clue about what is going on.
Sorry for bad style, i just wanted to drop the info, not fix it.

**Comment by zethfoxster** [comment]
also stopped working in auto1111
