### ISSUE TITLE
Does not work with a runtime error in the cli

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#4]
No matter which embs I try and merge.

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backend_bases.py", line 3036, in _wait_cursor_for_draw_cm
    self.canvas.set_cursor(tools.Cursors.WAIT)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 408, in set_cursor
    self._tkcanvas.configure(cursor=cursord[cursor])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 930, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 3693, in postprocess
    out_y = processing_utils.encode_plot_to_base64(y)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 103, in encode_plot_to_base64
    plt.savefig(output_bytes, format="png")
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\_api\deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 517, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 463, in _print_pil
    FigureCanvasAgg.draw(self)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    with RendererAgg.lock, \
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backend_bases.py", line 3039, in _wait_cursor_for_draw_cm
    self.canvas.set_cursor(self._last_cursor)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 408, in set_cursor
    self._tkcanvas.configure(cursor=cursord[cursor])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop

**Comment by tkalayci71** [comment]
Hi. I think this is an issue with matplotlib, I can't resolve it right now, so I disabled the graph as it wasn't required for saving. Please try latest version. Thank you.

**Comment by DarkAlchy** [comment]
> Hi. I think this is an issue with matplotlib, I can't resolve it right now, so I disabled the graph as it wasn't required for saving. Please try latest version. Thank you.

+ darth([ed98]) x 0.8
+ mal([efd2]) x 0.2
Saved "embeddings/steamdth.bin"
Reloading all embeddings

100% was in the plot.

Thanks.

**Comment by tkalayci71** [comment]
I think I got the graph working now, please test, thanks.

**Comment by DarkAlchy** [comment]
> I think I got the graph working now, please test, thanks.

It works now, but no idea what I am seeing is.  From the original documentation on TI I can see some things but it is so compressed it becomes meaningless.

![image](https://user-images.githubusercontent.com/10561690/210027013-3cbcbee4-e864-4abe-bbf9-dc4ebc3b524c.png)
